[package]
name = "game_actions"
version = "1.0.0"
edition = "2021"

[dependencies]
tui = {path = "../tui", version = "1.0.0"}
uuid = { version = "1.1.2", features = ["v4"] }
serde = { version = "1.0.144", features = ["derive"] }