[package]
name = "minesweeper_engine"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.5"
crossterm = { version = "0.25" }
log = "0.4.17"
queues = "1.0.2"